# Generated by Django 2.1.7 on 2019-03-10 22:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RefGenome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100)),
                ('path', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date_submit', models.DateTimeField(auto_now_add=True)),
                ('nr_of_seqs_fout', models.IntegerField(default=None, null=True)),
                ('fout_avg_quality', models.FloatField(default=None, null=True)),
                ('fin_avg_quality', models.FloatField(default=None, null=True)),
                ('collected_pairs', models.IntegerField(default=None, null=True)),
                ('analysis_time', models.FloatField(default=None, null=True)),
                ('libtype', models.CharField(default=None, max_length=10, null=True)),
                ('inwfwd', models.IntegerField(default=None, null=True)),
                ('inwrvs', models.IntegerField(default=None, null=True)),
                ('outfwd', models.IntegerField(default=None, null=True)),
                ('outrvs', models.IntegerField(default=None, null=True)),
                ('single', models.BooleanField(default=None)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('refgenome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guess.RefGenome')),
            ],
        ),
    ]
