"""
Django settings for GuessLib project.

Generated by 'django-admin startproject' using Django 2.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os
<<<<<<< HEAD
=======
import json

with open('/etc/config.json') as config_file:
    config = json.load(config_file)
>>>>>>> f54b90092c6a6fb9f26da8faad07ddf5460a4828

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PROJECT_ROOT = os.path.abspath(os.path.dirname(__file__))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
<<<<<<< HEAD
SECRET_KEY = 'xe)&(sa%6w-4f$*7l&8mzv5jaq-=gz*4@l5$#my_n!u$z3l&s4'
=======
SECRET_KEY = config['SECRET_KEY']
>>>>>>> f54b90092c6a6fb9f26da8faad07ddf5460a4828

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

<<<<<<< HEAD
ALLOWED_HOSTS = []
=======
ALLOWED_HOSTS = ['172.104.132.177', 'localhost', '127.0.0.1']
>>>>>>> f54b90092c6a6fb9f26da8faad07ddf5460a4828


# Application definition

INSTALLED_APPS = [
    'users.apps.UsersConfig',
    'guess.apps.GuessConfig',
    'captcha',
    'crispy_forms',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]


ACCOUNT_ACTIVATION_DAYS = 7

REGISTRATION_FORM = 'users.forms.RecaptchaRegistrationForm'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'GuessLib.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'GuessLib.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
<<<<<<< HEAD
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
=======

    'default': {

        'ENGINE': 'django.db.backends.mysql',

        'NAME': config['RDS_NAME'],

        'USER': config['RDS_USER'],

        'PASSWORD': config['RDS_PASSWORD'],

        'HOST': 'aa1a2sk105fsuzc.cnl7vpbtcyho.us-east-2.rds.amazonaws.com',

        'PORT': '3306',

        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES', innodb_strict_mode=1",
            'charset': 'utf8mb4',
        },
        'TEST': {
            'CHARSET': 'utf8mb4',
            'COLLATION': 'utf8mb4_unicode_ci',
        },

    }

>>>>>>> f54b90092c6a6fb9f26da8faad07ddf5460a4828
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
    {
        'NAME': 'GuessLib.validators.SpecialCharValidator',
    },
    {
        'NAME': 'GuessLib.validators.WhiteSpaceValidator',
    },
]

PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher'
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static/')


MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')
MEDIA_URL = "/media/"

CRISPY_TEMPLATE_PACK = 'bootstrap4'

LOGIN_REDIRECT_URL = 'guess-home'
LOGIN_URL = 'login'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
<<<<<<< HEAD
EMAIL_HOST_USER = 'guesslib@gmail.com'
EMAIL_HOST_PASSWORD = 'wyowgtxqbzvwnisz'

RECAPTCHA_PUBLIC_KEY = '6Le5bpYUAAAAAFhJfmqXFQ1TrcL68EiI3pkkBoTP'

RECAPTCHA_PRIVATE_KEY = '6Le5bpYUAAAAAFD_kG4_T0w2bqTDcqmWrK5Mn2XZ'
=======
EMAIL_HOST_USER = config['EMAIL_USER']
EMAIL_HOST_PASSWORD = config['EMAIL_PASS']

# RECAPTCHA_PUBLIC_KEY = '6Le5bpYUAAAAAFhJfmqXFQ1TrcL68EiI3pkkBoTP'

# RECAPTCHA_PRIVATE_KEY = '6Le5bpYUAAAAAFD_kG4_T0w2bqTDcqmWrK5Mn2XZ'

RECAPTCHA_PUBLIC_KEY = config['RECAPTCHA_PUBLIC']

RECAPTCHA_PRIVATE_KEY = config['RECAPTCHA_PRIVATE']

# CELERY STUFF
BROKER_URL = 'redis://localhost:6379'
CELERY_RESULT_BACKEND = 'redis://localhost:6379'
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

FILE_UPLOAD_PERMISSIONS = 0o644
>>>>>>> f54b90092c6a6fb9f26da8faad07ddf5460a4828
